export const DEMO_CAMPAIGNS = [
  {
    id: 'camp1',
    name: 'Summer Product Launch',
    status: 'active',
    objective: 'Awareness',
    channels: ['instagram', 'facebook', 'linkedin'],
    budget: 2500,
    spent: 1420,
    startDate: '2026-05-01',
    endDate: '2026-06-15',
    aiScore: 87,
    postsScheduled: 24,
    postsPublished: 18,
    reach: 48200,
    conversions: 312,
    brief: 'Launch our new AI scheduling feature with teaser content, demo Reels, and customer testimonials.',
  },
  {
    id: 'camp2',
    name: 'LinkedIn Thought Leadership',
    status: 'active',
    objective: 'Engagement',
    channels: ['linkedin', 'twitter'],
    budget: 800,
    spent: 520,
    startDate: '2026-05-10',
    endDate: '2026-05-31',
    aiScore: 92,
    postsScheduled: 12,
    postsPublished: 8,
    reach: 12400,
    conversions: 89,
    brief: 'Weekly insights on social media strategy for B2B marketers. Thread + carousel format.',
  },
  {
    id: 'camp3',
    name: 'UGC Hashtag Challenge',
    status: 'draft',
    objective: 'Community',
    channels: ['instagram', 'tiktok'],
    budget: 1500,
    spent: 0,
    startDate: '2026-06-01',
    endDate: '2026-06-30',
    aiScore: null,
    postsScheduled: 0,
    postsPublished: 0,
    reach: 0,
    conversions: 0,
    brief: 'Encourage users to share their content calendar setup with #ScheduleSmarter.',
  },
  {
    id: 'camp4',
    name: 'Q1 Retargeting — Webinar',
    status: 'completed',
    objective: 'Conversions',
    channels: ['facebook', 'linkedin', 'email'],
    budget: 3200,
    spent: 3180,
    startDate: '2026-03-01',
    endDate: '2026-03-31',
    aiScore: 78,
    postsScheduled: 16,
    postsPublished: 16,
    reach: 62100,
    conversions: 847,
    brief: 'Drive registrations for "Scale Your Social in 2026" webinar series.',
  },
];

export const AI_CAMPAIGN_SUGGESTIONS = {
  captions: [
    'Ready to post smarter, not harder? Our AI finds your best times automatically. Try free → link in bio.\n\n#SocialMedia #MarketingTools',
    'Your competitors are scheduling 2× more content. Close the gap with one afternoon of batch planning. Start today.',
  ],
  audiences: ['SMB marketers', 'Agency social managers', 'Content creators 10k–100k followers'],
  adAngles: ['Save 5+ hours/week', 'Beat algorithm timing', 'Multi-platform in one click'],
};

export const CAMPAIGN_OBJECTIVES = ['Awareness', 'Engagement', 'Conversions', 'Community', 'Lead generation'];
